(********************************************************************)
(*                             TETRIS                               *)
(*             Par Julien FAUCHER et Raphaël DIAZ                   *)
(********************************************************************)

include "pieces.ml";;
include "variable.ml";;
include "espace.ml";;
include "affiche.ml";;
include "ia.ml";;
include "jeu.ml";;
print_string "Pour lancer : tetris();;";
print_newline();;

